/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uc_lang_OSClock */

#ifndef _Included_uc_lang_OSClock
#define _Included_uc_lang_OSClock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uc_lang_OSClock
 * Method:    currentTimeMillis
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_uc_lang_OSClock_currentTimeMillis
  (JNIEnv *, jclass);

/*
 * Class:     uc_lang_OSClock
 * Method:    nanoTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_uc_lang_OSClock_nanoTime
  (JNIEnv *, jclass);

/*
 * Class:     uc_lang_OSClock
 * Method:    getEpochSecond
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_uc_lang_OSClock_getEpochSecond
  (JNIEnv *, jclass);

/*
 * Class:     uc_lang_OSClock
 * Method:    getEpochMillis
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_uc_lang_OSClock_getEpochMillis
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif